#ifndef _CPU_BEAM_H_
#define _CPU_BEAM_H_

#include "../../common/para.h"

#define TKK_NUM 19200
#define BTT_NUM (TKK_NUM/TK_NUM)

#define LOOP_NUM (BTT_NUM)
#define sub_task (TK_NUM)
#define NUM_CHANNELS (LOOP_NUM*sub_task)
#define THREADSTACK  65536

#define NUM_SAMPLES 2048
#define NUM_BEAMS 4
/* Bill writes: under current implementation, decimation ratios must
   divide NUM_SAMPLES. */
#define NUM_COARSE_TAPS 256
#define NUM_FINE_TAPS 256
#define COARSE_DECIMATION_RATIO 1
#define FINE_DECIMATION_RATIO 2
#define NUM_SEGMENTS 1
#define NUM_POST_DEC_1 (NUM_SAMPLES/COARSE_DECIMATION_RATIO)
#define NUM_POST_DEC_2 (NUM_POST_DEC_1/FINE_DECIMATION_RATIO)
#define MF_SIZE (NUM_SEGMENTS*NUM_POST_DEC_2)
#define PULSE_SIZE (NUM_POST_DEC_2/2)
#define PREDEC_PULSE_SIZE \
  (PULSE_SIZE*COARSE_DECIMATION_RATIO*FINE_DECIMATION_RATIO)
#define TARGET_BEAM (NUM_BEAMS/4)
#define TARGET_SAMPLE (NUM_SAMPLES/4)
#define TARGET_SAMPLE_POST_DEC \
   (TARGET_SAMPLE/COARSE_DECIMATION_RATIO/FINE_DECIMATION_RATIO)
#define D_OVER_LAMBDA 0.5
#define CFAR_THRESHOLD (0.95*D_OVER_LAMBDA*NUM_CHANNELS*0.5*PULSE_SIZE)

#endif
